server:
  port: 8081

spring:
  application:
    name: productservice
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  data:
    mongodb:
      uri: mongodb://mongodb:27017/productos
      auto-index-creation: true
  mongodb:
    connect-timeout: 2000
    socket-timeout: 2000
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      cloudwatch:
        endpoint: http://localstack:4566
      logging:
        log-group: practica-microservicios
        log-stream: productos-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
